// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSDGOU9UTPoRYkUzKWXhCLB1wqLqQxOFs',
    appId: '1:637620845590:web:9dd22622d4f670c96b4937',
    messagingSenderId: '637620845590',
    projectId: 'cineflix-12950',
    authDomain: 'cineflix-12950.firebaseapp.com',
    storageBucket: 'cineflix-12950.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM1OdIywRQ4hYCEQP4fxpIvsg6hPQ50jM',
    appId: '1:637620845590:android:4f3a9599f9f1ecd56b4937',
    messagingSenderId: '637620845590',
    projectId: 'cineflix-12950',
    storageBucket: 'cineflix-12950.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDurRKya4-8hy5sJG1Kdtj2DZzQaJEzuao',
    appId: '1:637620845590:ios:f8c2d107f3cacd956b4937',
    messagingSenderId: '637620845590',
    projectId: 'cineflix-12950',
    storageBucket: 'cineflix-12950.firebasestorage.app',
    iosBundleId: 'com.example.cineflixApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDurRKya4-8hy5sJG1Kdtj2DZzQaJEzuao',
    appId: '1:637620845590:ios:f8c2d107f3cacd956b4937',
    messagingSenderId: '637620845590',
    projectId: 'cineflix-12950',
    storageBucket: 'cineflix-12950.firebasestorage.app',
    iosBundleId: 'com.example.cineflixApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSDGOU9UTPoRYkUzKWXhCLB1wqLqQxOFs',
    appId: '1:637620845590:web:1b12dca60152bc536b4937',
    messagingSenderId: '637620845590',
    projectId: 'cineflix-12950',
    authDomain: 'cineflix-12950.firebaseapp.com',
    storageBucket: 'cineflix-12950.firebasestorage.app',
  );
}
